
kube:
  debugger: true
  manyEnv: false
server:
  port: 8890
  servlet:
    context-path: /api
  # 解决Tomcat问题
  tomcat:
    max-http-header-size: 10240000
    max-http-post-size: 10240000
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml   # 配置mapper的扫描，找到所有的mapper.xml映射文件
  type-aliases-package: com.auto.test.entity  # 注意：对应实体类的路径
  #开启驼峰转换
  configuration:
    mapUnderscoreToCamelCase: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://localhost:3306/auto_test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: zea0i+6hx7Dp
      #配置初始化大小/最小/最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        enabled: true
        url-pattern: /monitor/druid/*
  profiles:
    active: prod
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #启动时加载
  mvc:
    servlet:
      load-on-startup: 0
  # 上传文件限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
swagger:
  enable: false #是否禁用swagger
logging:
  level:
    com:
      rabbit:
        dao : debug
  config: classpath:logback-admin.xml

#token过期时间设置
token:
  expire:
    seconds: 86400 # token过期时间，24个小时
  jwtSecret: (XIAO:)_$^11244^%$_(WEI:)_@@++--(LAO:)_++++_.sds_(SHI:)

log:
  level:
    #日志级别从低到高分为：
    #  配置TRACE < DEBUG < INFO < WARN < ERROR < FATAL
    root: INFO
    my: DEBUG
  file: logs/admin-server.log
  maxsize: 10MB